config/routes.rb
Rails.application.routes.draw do
  root 'blogs#index'
  resources :blogs
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, :content, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true

  before_validation { email.downcase! }

  has_secure_password

  has_many :blogs
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :update, :show, :destroy]

  def index
    @blogs = Blog.all.order(created_at: :desc)
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    if @blog.save
      redirect_to blogs_path
      flash[:notice] = "作成しました"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @blog = Blog.update(blog_params)
    if @blog.update
      redirect_to blogs_path
      flash[:notice] = "更新しました"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path
    flash[:notice] = "削除しました"
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to blogs_path
      flash[:notice] = "ログインしました"
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user.id), notice: "ユーザ「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "ユーザ「#{@user.name}」を更新しました。"
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to new_users_path, notice: "ユーザ「#{@user.name}」を削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.slim
= form_with(model: @blog, lcoal:true) do |f|
  div
    = f.label :title
    = f.text_field :title
  div
    = f.label :content
    = f.text_area :content
  div
    = f.submit "登録"
    = link_to "戻る", blogs_path

app/views/blogs/edit.html.slim
h1
  | Edit Blog
= render 'form'

app/views/blogs/index.html.slim
h1
  | Blogs一覧
= link_to "New Blog", new_blog_path
- @blogs.each do |blog|
  p
    | Title: 
    = blog.title
  p
    | Content: 
    = blog.content
  = link_to "Show", blog_path(blog)
  = link_to 'Delete', blog_path(blog), method: :delete, data: {confirm: "削除しますか？"}

app/views/blogs/new.html.slim
h1
  | New Blog

= render partial: 'form', locals: { blog: @blog }

app/views/blogs/show.html.slim
h1
  | Blogs
div
  p
    | Title: 
    = @blog.title
  p
    | Content: 
    = @blog.content
= link_to "戻る", blogs_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | DicDay10
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    - flash.each do |key, value|
      = content_tag(:div, value, class:"#{key}")
    - if logged_in?
      = link_to "My profile", user_path(current_user.id)
      = link_to "Logout", session_path(current_user.id), method: :delete
      = link_to "NewBlog", session_path(current_user.id)
      = link_to "Users", session_path(current_user.id)
    - else
      = link_to "Sign up", new_user_path
      = link_to "Login", new_session_path
    = yield

app/views/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li= message

= form_with model: user, local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード(確認)'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/users/edit.html.slim
h1 ユーザの編集

.nav.justify-content-end
  = link_to '一覧', users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/users/new.html.slim
h1 ユーザ登録

= render partial: 'form', locals: { user: @user }

app/views/users/show.html.slim
h1 ユーザの詳細

table.table.table-hover
  tbody
    tr
      th メールアドレス
      td = @user.email
    tr
      th 名前
      td = @user.name
    tr

= link_to '編集', edit_user_path(@user), class: 'btn btn-primary mr-3'
= link_to '削除', user_path(@user), method: :delete, data: { confirm: "ユーザ「#{@user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'